[package]
name = "telnet-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
tokio = { version = "1", features = ["full"] }
#tokio = { version = "1", features = ["tokio-macros", "rt", "rt-multi-thread", "macros", "net"] }
