[package]
name = "telnet-chat-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "rt-multi-thread", "macros", "net", "sync", "io-std", "io-util"] }
tokio_schedule = "0.3.2"
#tokio = { version = "1", features = ["full"] }
